parameters:
    ### Pim models
    pim_catalog.entity.product_value.class: CleverAge\Bundle\GeolocAttributeBundle\Model\ProductValue

    ### Bundle models
    cleverage.geolocation.model.geolocation.class: CleverAge\Bundle\GeolocAttributeBundle\Model\Geolocation
