parameters:
    ### Bundle classes
    cleverage.geolocation.attribute_type.class: CleverAge\Bundle\GelocAttributeBundle\AttributeType\GeolocationType
    cleverage.geolocation.form_type.class: CleverAge\Bundle\GelocAttributeBundle\Form\Type\GeolocationType
    cleverage.geolocation.normalizer.class: CleverAge\Bundle\GelocAttributeBundle\Form\Type\GeolocationType

    ### Geolocation datagrid configuration
    pim_datagrid.product.attribute_type.cleverage_attribute_geolocation:
        column:
            type:        product_value_field
            selector:    product_value_base
        filter: ~
        sorter: ~

services:
    cleverage.geolocation.attribute_type:
        class: %cleverage.geolocation.attribute_type.class%
        arguments:
            - geolocation
            - cleverage_form_geolocation
            - '@pim_catalog.validator.constraint_guesser.chained_attribute'
        tags:
            - { name: pim_catalog.attribute_type, alias: cleverage_attribute_geolocation, entity: %pim_catalog.entity.product.class% }

    cleverage.geolocation.form_type:
        class: %cleverage.geolocation.form_type.class%
        arguments:
            - %cleverage.geolocation.model.geolocation.class%
        tags:
            - { name: form.type, alias: cleverage_form_geolocation }

    cleverage.gelocation.normalizer:
        class: %cleverage.geolocation.normalizer.class%
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }
            - { name: pim_versioning.serializer.normalizer, priority: 90 }