parameters:
    cleverage.geolocation.metadata_subscriber.class: CleverAge\Bundle\GelocAttributeBundle\Model\ProductValue

services:
    cleverage.geolocation.metadata_subscriber:
        class: %cleverage.geolocation.metadata_subscriber.class%
        arguments:
            - %pim_catalog.entity.product_value.class%
            - %cleverage.geolocation.model.class%
