parameters:
    ### Models
    cleverage.geolocation.model.product_value.class: CleverAge\Bundle\GelocAttributeBundle\Model\ProductValue
    cleverage.geolocation.model.geolocation.class: CleverAge\Bundle\GelocAttributeBundle\Model\Geolocation
