parameters:
    ### Pim classes
    pim_catalog.entity.product_value.class: CleverAge\Bundle\GelocAttributeBundle\Model\ProductValue

    ### Bundle classes
    cleverage.geolocation.model.class: CleverAge\Bundle\GelocAttributeBundle\Model\Geolocation
