config:
    shim:
        addresspicker:
            deps:
                - typeahead
    paths:
        async: cleveragegeolocattribute/js/vendors/requirejs/async
        typeahead: cleveragegeolocattribute/js/vendors/typeahead/typeahead
        addresspicker: cleveragegeolocattribute/js/vendors/addresspicker/addresspicker
