CleverAge\Bundle\GeolocAttributeBundle\Model\Geolocation:
    properties:
        latitude:
            - Range:
                min: -90
                max: 90
        longitude:
            - Range:
                min: -180
                max: 180
